const doctors = [
  {
    id: 1,
    name: "Dr. Ankit Sharma",
    gender: "male",
    specialty: "Cardiologist",
    experience: 10,
    rating: 4.8,
    hospital: "AIIMS Delhi",
    city: "Delhi",
    fee: 800,
    image: "/doctors/male.svg",
    available: true,
    fees: 300
  },
  {
    id: 2,
    name: "Dr. Neha Verma",
    gender: "female",
    specialty: "Dermatologist",
    experience: 7,
    rating: 4.6,
    hospital: "Apollo Hospital",
    city: "Noida",
    fee: 600,
    image: "/doctors/female.svg",
    available: true,
    fees: 400
  },
  {
    id: 3,
    name: "Dr. Rohit Gupta",
    gender: "male",
    specialty: "Orthopedic",
    experience: 12,
    rating: 4.7,
    hospital: "Fortis",
    city: "Gurgaon",
    fee: 900,
    image: "/doctors/male.svg",
    available: false,
    fees: 500
  },
  {
    id: 4,
    name: "Dr. Pooja Singh",
    gender: "female",
    specialty: "Gynecologist",
    experience: 9,
    rating: 4.9,
    hospital: "Max Hospital",
    city: "Delhi",
    fee: 700,
    image: "/doctors/female.svg",
    available: true,
    fees: 300
  },
  {
    id: 5,
    name: "Dr. Sandeep Mehta",
    gender: "male",
    specialty: "Neurologist",
    experience: 15,
    rating: 4.8,
    hospital: "Medanta",
    city: "Gurgaon",
    fee: 1200,
    image: "/doctors/male.svg",
    available: true,
    fees: 600
  },
  {
    id: 6,
    name: "Dr. Riya Kapoor",
    gender: "female",
    specialty: "Pediatrician",
    experience: 6,
    rating: 4.5,
    hospital: "Cloudnine",
    city: "Noida",
    fee: 500,
    image: "/doctors/female.svg",
    available: true,
    fees: 350
  },
  {
    id: 7,
    name: "Dr. Amit Mishra",
    gender: "male",
    specialty: "General Physician",
    experience: 8,
    rating: 4.4,
    hospital: "Max Hospital",
    city: "Ghaziabad",
    fee: 400,
    image: "/doctors/male.svg",
    available: true,
    fees: 250
  },
  {
    id: 8,
    name: "Dr. Shalini Arora",
    gender: "female",
    specialty: "ENT Specialist",
    experience: 11,
    rating: 4.7,
    hospital: "Fortis",
    city: "Faridabad",
    fee: 650,
    image: "/doctors/female.svg",
    available: false,
    fees: 450
  },
  {
    id: 9,
    name: "Dr. Prakash Nair",
    gender: "male",
    specialty: "Psychiatrist",
    experience: 14,
    rating: 4.6,
    hospital: "AIIMS",
    city: "Delhi",
    fee: 1000,
    image: "/doctors/male.svg",
    available: true,
    fees: 550
  },
  {
    id: 10,
    name: "Dr. Sunita Joshi",
    gender: "female",
    specialty: "Dentist",
    experience: 10,
    rating: 4.5,
    hospital: "Clove Dental",
    city: "Noida",
    fee: 450,
    image: "/doctors/female.svg",
    available: true,
    fees: 300
  },
  {
    id: 11,
    name: "Dr. Kunal Bansal",
    gender: "male",
    specialty: "Urologist",
    experience: 13,
    rating: 4.7,
    hospital: "Medanta",
    city: "Gurgaon",
    fee: 1100,
    image: "/doctors/male.svg",
    available: false,
    fees: 600
  },
  {
    id: 12,
    name: "Dr. Aarti Malhotra",
    gender: "female",
    specialty: "Nutritionist",
    experience: 5,
    rating: 4.3,
    hospital: "Private Clinic",
    city: "Delhi",
    fee: 350,
    image: "/doctors/female.svg",
    available: true,
    fees: 200
  },
  {
    id: 13,
    name: "Dr. Harsh Vardhan",
    gender: "male",
    specialty: "Oncologist",
    experience: 18,
    rating: 4.9,
    hospital: "Max Cancer Center",
    city: "Delhi",
    fee: 1500,
    image: "/doctors/male.svg",
    available: true,
    fees: 800
  },
  {
    id: 14,
    name: "Dr. Nidhi Kulshrestha",
    gender: "female",
    specialty: "Pathologist",
    experience: 9,
    rating: 4.4,
    hospital: "SRL Diagnostics",
    city: "Noida",
    fee: 500,
    image: "/doctors/female.svg",
    available: true,
    fees: 300
  },
  {
    id: 15,
    name: "Dr. Manish Chauhan",
    gender: "male",
    specialty: "Pulmonologist",
    experience: 14,
    rating: 4.6,
    hospital: "Fortis",
    city: "Gurgaon",
    fee: 900,
    image: "/doctors/male.svg",
    available: true,
    fees: 500
  },
  {
    id: 16,
    name: "Dr. Kavita Jain",
    gender: "female",
    specialty: "Ophthalmologist",
    experience: 12,
    rating: 4.8,
    hospital: "Eye7 Hospital",
    city: "Delhi",
    fee: 750,
    image: "/doctors/female.svg",
    available: true,
    fees: 400
  },
  {
    id: 17,
    name: "Dr. Suresh Yadav",
    gender: "male",
    specialty: "Surgeon",
    experience: 20,
    rating: 4.9,
    hospital: "AIIMS",
    city: "Delhi",
    fee: 2000,
    image: "/doctors/male.svg",
    available: false,
    fees: 1000
  },
  {
    id: 18,
    name: "Dr. Bhavya Aggarwal",
    gender: "female",
    specialty: "Physiotherapist",
    experience: 6,
    rating: 4.3,
    hospital: "Private Clinic",
    city: "Ghaziabad",
    fee: 400,
    image: "/doctors/female.svg",
    available: true,
    fees: 250
  },
  {
    id: 19,
    name: "Dr. Rakesh Tripathi",
    gender: "male",
    specialty: "Endocrinologist",
    experience: 16,
    rating: 4.8,
    hospital: "Medanta",
    city: "Gurgaon",
    fee: 1300,
    image: "/doctors/male.svg",
    available: true,
    fees: 700
  },
  {
    id: 20,
    name: "Dr. Meenal Chaturvedi",
    gender: "female",
    specialty: "Radiologist",
    experience: 11,
    rating: 4.6,
    hospital: "Max Diagnostics",
    city: "Noida",
    fee: 850,
    image: "/doctors/female.svg",
    available: true,
    fees: 450
  },
];

export default doctors;
